#!/bin/bash
yum update -y
#Updates the package repository and installs any available updates
yum install -y httpd
#Installs Apache web server (HTTPD) package
service httpd start
#Starts the Apache web server
chkconfig httpd on
#Configures Apache to start automatically upon instance boot
echo "<html><body><h1>Welcome to My Website!</h1><p>This content is served by an EC2 instance launched by an Auto Scaling Group.</p></body></html>" > /var/www/html/index.html

#chkconfig: This command manages with services start automatically at differnt runtimes
#httpd: This refers to the Apache HTTP server service
#on: This option enables the service to start at boot time
